# Generated by Django 2.2.17 on 2021-01-23 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='big_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
