# Generated by Django 2.2.17 on 2021-01-24 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_big_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='big_text',
        ),
    ]
